### ISSUE TITLE
Null Pointer post init

### ISSUE THREAD

**Issue by coalman321** [jcorcoran/BNO055_FRC#13] opened 2016-11-26 04:29 UTC
I seem to be having a wired null pointer bouncing around after trying to get the sensor's state in auto for testing purposes. assuming the .getInstance is the correct way to instantiate the object, my code seems fine other than the obvious null pointer. i have put the code in a gist. I am trying to get the BNO working for one of our team's side projects. any help you can give would be greatly appreciated.
Thanks,
Cole 
Team 4145
electrical and programming 
https://gist.github.com/coalman321/e7923d4dcd3adaf0e875b79ca422cca7

**Comment by jcorcoran** [comment] 2016-11-26 15:44
It looks like you are creating a local instance of a BNO055 object inside your Robot class: https://gist.github.com/coalman321/e7923d4dcd3adaf0e875b79ca422cca7#file-robot-java-L41

Then later on, all the operations act on this local copy of the 'sensor" object.

The problem with your code is that the "sensor" object isn't instantiated at the time you assign it, because the RobotMap.init() method hasn't been called until the Robot.robotInit method is called. 

My suggested solution is to not create a local copy of the sensor object in your Robot class (delete line 41 in Robot.java), then inside the autonomousInit() method, replace all the calls to "sensor." with "RobotMap.sensor."

You must remember though, that none of the objects within RobotMap are instantiated until after RobotMap.init is called. This is the cause of your problem... so it could be elsewhere in your code as well. In general, it's a bad idea to instantiate objects were they are declared, because of this issue you've run into above.

**Closed as completed by jcorcoran** 2016-11-26 15:44 UTC
Labels: question
